#! /bin/bash

prefix=lxc
export VAGRANT_CWD=vagrantfiles
boxes=$(ls vagrantfiles)
boxes=(debian-jessie)

for file in ${boxes[@]}; do
  box_name="${prefix}-${file}"
  export VAGRANT_VAGRANTFILE=${file}

  vagrant destroy -f
  vagrant up

  vagrant package --output ${box_name}.box
  vagrant box add --force ${box_name} ${box_name}.box
  rm -f ${box_name}.box
done
