require "yaml"

Vagrant::DEFAULT_SERVER_URL.replace('https://vagrantcloud.com')

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
# Vagrant configuration for base image #
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

IMAGE = 'debian/stretch64'
NODE  = 'vagrant-lxc-base-box'

Vagrant.configure(2) do |config|
  config.vm.box = IMAGE
  config.vm.define NODE do |node|
    node.vm.hostname = NODE
    node.vm.provider :lxc do |lxc|
      lxc.container_name = :machine
      lxc.customize 'network.link', 'lxc-bridge'
    end

    #
    # Run Ansible from the Vagrant Host
    #
    config.vm.provision "ansible", run: "always" do |ansible|
      ansible.playbook    = "#{ENV['ANSIBLE_PERSONAL_PATH']}/playbooks/#{ENV['BOX_TO_GENERATE']}/playbook.yml"
      ansible.config_file = ENV['ANSIBLE_PERSONAL_CONFIG']
      ansible.groups = {
        "vagrant-box" => ["vagrant-lxc-base-box"]
      }
    end
  end
end