#! /bin/bash

prefix=libvirt
export VAGRANT_CWD=Vagrantfiles

for file in $(ls Vagrantfiles); do
  box_name="${prefix}-${file}"
  export VAGRANT_VAGRANTFILE=${file}

  vagrant destroy -f
  vagrant up

  sudo chmod -R a+r /var/lib/libvirt/images/*

  vagrant package --output ${box_name}.box
  vagrant box add --force ${box_name} ${box_name}.box
  rm -f ${box_name}.box
done