#! /bin/bash

prefix=libvirt
export VAGRANT_CWD=Vagrantfiles

for file in $(ls Vagrantfiles); do
  box_name="libvirt-${file}"
  export VAGRANT_VAGRANTFILE=${file}

  vagrant destroy -f
  vagrant up

  sudo chmod -R a+r /var/lib/libvirt/images/*

  vagrant package --output ${box_name}.box
  vagrant box add --force ${box_name} ${box_name}.box
  rm -f ${box_name}.box
done

function finish {
  echo "----> Clean all existing vagrant machines"
  vagrant destroy -f $(vagrant global-status | egrep -o "^[0-9a-f]+")
}
trap finish INT EXIT